<?php

/**
 * Created by PhpStorm.
 * User: usuario
 * Date: 29/11/2016
 * Time: 10:44
 */
require_once("Tarea.php");
class ComandoSO extends Tarea
{
    public function doEjecutar()
    {
        parent::doEjecutar(); // TODO: Change the autogenerated stub
    }
}