<?php

/**
 * Created by PhpStorm.
 * User: usuario
 * Date: 29/11/2016
 * Time: 11:14
 */
require_once("TareaProgramada.php");
class UnicaVez extends TareaProgramada
{
    /**
     * @return: boolean
     */
    public function correspondeEjecutar()
    {
        parent::correspondeEjecutar(); // TODO: Change the autogenerated stub
    }


}